In [1]:
import pandas as pd
import numpy as np

In [165]:
df = pd.read_csv("Borough_tree_list.csv")
df_treeRef = pd.read_csv("Tree_type.csv")
df_boroughRent = pd.read_csv("Borough_rent.csv")
df_treeLoc = pd.read_csv("location_Trees.csv")

In [166]:
df_boroughRent.head()

                borough Borough House Prices (nov 2025)  Borough_Nut_Rent
0  Barking and Dagenham                          357257               485
1                Barnet                         603,111               819
2                Bexley                         410,560               558
3                 Brent                         542,514               737
4               Bromley                         534,443               726

In [167]:
df_treeRef.head()

                Tree Food squirrels can eat (Yes / No)
0              Maple                               Yes
1        Field Maple                               Yes
2                Ash                               Yes
3  Cappadocian Maple                               Yes
4      Ashleaf Maple                               Yes

In [168]:
df = df.rename(columns= {"common_name": "Tree"})

In [169]:
print(df.head())

  borough        lat       lon  uniqueid taxon_species   Tree taxon_genus  \
0  Barnet  51.631685 -0.144650        69          Acer  Maple        Acer
1  Barnet  51.657878 -0.199403        70          Acer  Maple        Acer
2  Barnet  51.634156 -0.136630        71          Acer  Maple        Acer
3  Barnet  51.635864 -0.138829        72          Acer  Maple        Acer
4  Barnet  51.633960 -0.138993        73          Acer  Maple        Acer

  common_genus gla_name taxon_family maintainer  location climate_suitability  \
0        Maple    Maple  Sapindaceae  LB Barnet     Other                 Low
1        Maple    Maple  Sapindaceae  LB Barnet     Other                 Low
2        Maple    Maple  Sapindaceae  LB Barnet  Highways                 Low
3        Maple    Maple  Sapindaceae  LB Barnet  Highways                 Low
4        Maple    Maple  Sapindaceae  LB Barnet  Highways                 Low

  cs_confidence       age_cat canopy_m height_m girth_dbh
0           Low  Not provided      8 m     10 m     32 cm
1           Low  Not provided      8 m     12 m     60 cm
2           Low  Not provided      6 m      7 m     32 cm
3           Low  Not provided      9 m     13 m     56 cm
4           Low  Not provided      2 m      3 m      5 cm

In [170]:
df["girth"] = pd.to_numeric(df["girth_dbh"].str.split(n=1).str[0], errors="coerce")
df["canopy"] = pd.to_numeric(df["canopy_m"].str.split(n=1).str[0], errors="coerce")
df["height"] = pd.to_numeric(df["height_m"].str.split(n=1).str[0], errors="coerce")

In [171]:
print(df.head())

  borough        lat       lon  uniqueid taxon_species   Tree taxon_genus  \
0  Barnet  51.631685 -0.144650        69          Acer  Maple        Acer
1  Barnet  51.657878 -0.199403        70          Acer  Maple        Acer
2  Barnet  51.634156 -0.136630        71          Acer  Maple        Acer
3  Barnet  51.635864 -0.138829        72          Acer  Maple        Acer
4  Barnet  51.633960 -0.138993        73          Acer  Maple        Acer

  common_genus gla_name taxon_family  ...  location climate_suitability  \
0        Maple    Maple  Sapindaceae  ...     Other                 Low
1        Maple    Maple  Sapindaceae  ...     Other                 Low
2        Maple    Maple  Sapindaceae  ...  Highways                 Low
3        Maple    Maple  Sapindaceae  ...  Highways                 Low
4        Maple    Maple  Sapindaceae  ...  Highways                 Low

  cs_confidence       age_cat canopy_m height_m girth_dbh girth  canopy  \
0           Low  Not provided      8 m     10 m     32 cm  32.0     8.0
1           Low  Not provided      8 m     12 m     60 cm  60.0     8.0
2           Low  Not provided      6 m      7 m     32 cm  32.0     6.0
3           Low  Not provided      9 m     13 m     56 cm  56.0     9.0
4           Low  Not provided      2 m      3 m      5 cm   5.0     2.0

   height
0    10.0
1    12.0
2     7.0
3    13.0
4     3.0

[5 rows x 21 columns]

In [172]:
left_join = pd.merge(df, df_treeRef, on='Tree', how='left')

In [173]:
left_join.head()

,borough,lat,lon,uniqueid,taxon_species,Tree,taxon_genus,common_genus,gla_name,taxon_family,...,climate_suitability,cs_confidence,age_cat,canopy_m,height_m,girth_dbh,girth,canopy,height,Food squirrels can eat (Yes / No)
0,Barnet,51.631685,-0.144650,69,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,Low,Low,Not provided,8 m,10 m,32 cm,32.0,8.0,10.0,Yes
1,Barnet,51.657878,-0.199403,70,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,Low,Low,Not provided,8 m,12 m,60 cm,60.0,8.0,12.0,Yes
2,Barnet,51.634156,-0.136630,71,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,Low,Low,Not provided,6 m,7 m,32 cm,32.0,6.0,7.0,Yes
3,Barnet,51.635864,-0.138829,72,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,Low,Low,Not provided,9 m,13 m,56 cm,56.0,9.0,13.0,Yes
4,Barnet,51.633960,-0.138993,73,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,Low,Low,Not provided,2 m,3 m,5 cm,5.0,2.0,3.0,Yes

In [174]:
left_join["Food squirrels can eat (Yes / No)"].describe()

count     1048486
unique          2
top           Yes
freq       974892
Name: Food squirrels can eat (Yes / No), dtype: object

In [175]:
tree_borough_join = pd.merge(left_join, df_boroughRent, on="borough", how='left')

In [176]:
tree_borough_join.head()

,borough,lat,lon,uniqueid,taxon_species,Tree,taxon_genus,common_genus,gla_name,taxon_family,...,age_cat,canopy_m,height_m,girth_dbh,girth,canopy,height,Food squirrels can eat (Yes / No),Borough House Prices (nov 2025),Borough_Nut_Rent
0,Barnet,51.631685,-0.144650,69,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,Not provided,8 m,10 m,32 cm,32.0,8.0,10.0,Yes,"603,111",819.0
1,Barnet,51.657878,-0.199403,70,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,Not provided,8 m,12 m,60 cm,60.0,8.0,12.0,Yes,"603,111",819.0
2,Barnet,51.634156,-0.136630,71,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,Not provided,6 m,7 m,32 cm,32.0,6.0,7.0,Yes,"603,111",819.0
3,Barnet,51.635864,-0.138829,72,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,Not provided,9 m,13 m,56 cm,56.0,9.0,13.0,Yes,"603,111",819.0
4,Barnet,51.633960,-0.138993,73,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,Not provided,2 m,3 m,5 cm,5.0,2.0,3.0,Yes,"603,111",819.0

In [177]:
tree_Age_p10 = tree_borough_join["girth"].quantile(0.1)
tree_Age_p90 = tree_borough_join["girth"].quantile(0.9)

In [178]:
def p10_p90(series: pd.Series) -> pd.Series:
    s=series[series > 0]
    if len(s) < 5:
        return pd.Series({"p10": np.nan, "p90": np.nan})
    return pd.Series({"p10": s.quantile(0.10), "p90": s.quantile(0.90)})

In [179]:
borough_stats = tree_borough_join.groupby("borough")["girth"].apply(p10_p90).reset_index()

In [180]:
borough_stats = borough_stats.pivot(index="borough", columns="level_1", values="girth").reset_index()

In [181]:
borough_stats.rename(columns={"p10": "P10_girth_borough", "p90": "P90_girth_borough"}, inplace=True)

In [182]:
borough_stats.head()

level_1               borough  P10_girth_borough  P90_girth_borough
0        Barking and Dagenham               15.0               60.0
1                      Barnet                6.0               65.0
2                      Bexley               10.0               56.0
3                       Brent                6.0               61.0
4                     Bromley               14.0               68.0

In [183]:
print(borough_stats["borough"].describe())

count                       33
unique                      33
top       Barking and Dagenham
freq                         1
Name: borough, dtype: object

In [184]:
tree_borough_join_G.head()

,borough,lat,lon,uniqueid,taxon_species,Tree,taxon_genus,common_genus,gla_name,taxon_family,...,P10_girth_borough,P90_girth_borough,GirthIndex,AgeFactor,TreeRent,CanopyScore,HeightScore,GirthScore,StructureScore,FoodScore
0,Barnet,51.631685,-0.144650,69,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,6.0,65.0,0.440678,1.076271,881.466102,0.205128,0.222222,0.107023,0.180825,1
1,Barnet,51.657878,-0.199403,70,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,6.0,65.0,0.915254,1.266102,1036.937288,0.205128,0.266667,0.200669,0.222252,1
2,Barnet,51.634156,-0.136630,71,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,6.0,65.0,0.440678,1.076271,881.466102,0.153846,0.155556,0.107023,0.140312,1
3,Barnet,51.635864,-0.138829,72,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,6.0,65.0,0.847458,1.238983,1014.727119,0.230769,0.288889,0.187291,0.235162,1
4,Barnet,51.633960,-0.138993,73,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,6.0,65.0,0.000000,0.900000,737.100000,0.051282,0.066667,0.016722,0.045530,1

In [185]:
tree_borough_join_G = pd.merge(tree_borough_join, borough_stats, on="borough", how='left')

In [186]:
#Girth & AgeFactor
denom = (tree_borough_join_G["P90_girth_borough"] - tree_borough_join_G["P10_girth_borough"]).replace(0, np.nan)
raw = (tree_borough_join_G["girth"] - tree_borough_join_G["P10_girth_borough"]) / denom
tree_borough_join_G["GirthIndex"] = raw.clip(lower=0, upper=1).fillna(0)

tree_borough_join_G["AgeFactor"] = 0.9 + 0.4 * tree_borough_join_G["GirthIndex"]

In [187]:
tree_borough_join_G.head()

,borough,lat,lon,uniqueid,taxon_species,Tree,taxon_genus,common_genus,gla_name,taxon_family,...,girth,canopy,height,Food squirrels can eat (Yes / No),Borough House Prices (nov 2025),Borough_Nut_Rent,P10_girth_borough,P90_girth_borough,GirthIndex,AgeFactor
0,Barnet,51.631685,-0.144650,69,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,32.0,8.0,10.0,Yes,"603,111",819.0,6.0,65.0,0.440678,1.076271
1,Barnet,51.657878,-0.199403,70,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,60.0,8.0,12.0,Yes,"603,111",819.0,6.0,65.0,0.915254,1.266102
2,Barnet,51.634156,-0.136630,71,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,32.0,6.0,7.0,Yes,"603,111",819.0,6.0,65.0,0.440678,1.076271
3,Barnet,51.635864,-0.138829,72,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,56.0,9.0,13.0,Yes,"603,111",819.0,6.0,65.0,0.847458,1.238983
4,Barnet,51.633960,-0.138993,73,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,5.0,2.0,3.0,Yes,"603,111",819.0,6.0,65.0,0.000000,0.900000

In [188]:
tree_borough_join_G["TreeRent"] = tree_borough_join_G["Borough_Nut_Rent"]*tree_borough_join_G["AgeFactor"]

In [189]:
tree_borough_join_G.head()

,borough,lat,lon,uniqueid,taxon_species,Tree,taxon_genus,common_genus,gla_name,taxon_family,...,canopy,height,Food squirrels can eat (Yes / No),Borough House Prices (nov 2025),Borough_Nut_Rent,P10_girth_borough,P90_girth_borough,GirthIndex,AgeFactor,TreeRent
0,Barnet,51.631685,-0.144650,69,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,8.0,10.0,Yes,"603,111",819.0,6.0,65.0,0.440678,1.076271,881.466102
1,Barnet,51.657878,-0.199403,70,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,8.0,12.0,Yes,"603,111",819.0,6.0,65.0,0.915254,1.266102,1036.937288
2,Barnet,51.634156,-0.136630,71,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,6.0,7.0,Yes,"603,111",819.0,6.0,65.0,0.440678,1.076271,881.466102
3,Barnet,51.635864,-0.138829,72,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,9.0,13.0,Yes,"603,111",819.0,6.0,65.0,0.847458,1.238983,1014.727119
4,Barnet,51.633960,-0.138993,73,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,2.0,3.0,Yes,"603,111",819.0,6.0,65.0,0.000000,0.900000,737.100000

In [190]:
tree_borough_join_G["CanopyScore"] = tree_borough_join_G["canopy"] / max(tree_borough_join_G["canopy"])
tree_borough_join_G["HeightScore"] = tree_borough_join_G["height"] / max(tree_borough_join_G["height"])
tree_borough_join_G["GirthScore"] = tree_borough_join_G["girth"] / max(tree_borough_join_G["girth"])

In [191]:
tree_borough_join_G["StructureScore"] = (0.4 * tree_borough_join_G["CanopyScore"]) + (0.3*tree_borough_join_G["HeightScore"]) + (0.3*tree_borough_join_G["GirthScore"])

In [192]:
tree_borough_join_G["FoodScore"] = tree_borough_join_G["Food squirrels can eat (Yes / No)"].str.strip().str.lower().map({
    "yes": 1,
    "no": 0
}).fillna(0).astype(int)

In [193]:
tree_borough_join_final = pd.merge(tree_borough_join_G, df_treeLoc, on="location", how='left')

In [194]:
tree_borough_join_final.head()

,borough,lat,lon,uniqueid,taxon_species,Tree,taxon_genus,common_genus,gla_name,taxon_family,...,GirthIndex,AgeFactor,TreeRent,CanopyScore,HeightScore,GirthScore,StructureScore,FoodScore,location_cat,SiteFactor
0,Barnet,51.631685,-0.144650,69,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,0.440678,1.076271,881.466102,0.205128,0.222222,0.107023,0.180825,1,1,1.0
1,Barnet,51.657878,-0.199403,70,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,0.915254,1.266102,1036.937288,0.205128,0.266667,0.200669,0.222252,1,1,1.0
2,Barnet,51.634156,-0.136630,71,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,0.440678,1.076271,881.466102,0.153846,0.155556,0.107023,0.140312,1,2,0.7
3,Barnet,51.635864,-0.138829,72,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,0.847458,1.238983,1014.727119,0.230769,0.288889,0.187291,0.235162,1,2,0.7
4,Barnet,51.633960,-0.138993,73,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,0.000000,0.900000,737.100000,0.051282,0.066667,0.016722,0.045530,1,2,0.7

In [195]:
tree_borough_join_final["Tree Value Score"] = 100*((0.5*tree_borough_join_final["StructureScore"])+(0.3*tree_borough_join_final["FoodScore"])+(0.2*tree_borough_join_final["SiteFactor"]))

In [196]:
tree_borough_join_final.head()

,borough,lat,lon,uniqueid,taxon_species,Tree,taxon_genus,common_genus,gla_name,taxon_family,...,AgeFactor,TreeRent,CanopyScore,HeightScore,GirthScore,StructureScore,FoodScore,location_cat,SiteFactor,Tree Value Score
0,Barnet,51.631685,-0.144650,69,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,1.076271,881.466102,0.205128,0.222222,0.107023,0.180825,1,1,1.0,59.041249
1,Barnet,51.657878,-0.199403,70,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,1.266102,1036.937288,0.205128,0.266667,0.200669,0.222252,1,1,1.0,61.112598
2,Barnet,51.634156,-0.136630,71,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,1.076271,881.466102,0.153846,0.155556,0.107023,0.140312,1,2,0.7,51.015608
3,Barnet,51.635864,-0.138829,72,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,1.238983,1014.727119,0.230769,0.288889,0.187291,0.235162,1,2,0.7,55.758082
4,Barnet,51.633960,-0.138993,73,Acer,Maple,Acer,Maple,Maple,Sapindaceae,...,0.900000,737.100000,0.051282,0.066667,0.016722,0.045530,1,2,0.7,46.276477

In [197]:
tree_borough_join_final["Rank"] = tree_borough_join_final["Tree Value Score"].rank(ascending=False)

In [198]:
tree_borough_join_final[["Tree Value Score", "Rank"]].isna()

         Tree Value Score   Rank
0                   False  False
1                   False  False
2                   False  False
3                   False  False
4                   False  False
...                   ...    ...
1048570             False  False
1048571             False  False
1048572             False  False
1048573             False  False
1048574             False  False

[1048575 rows x 2 columns]

In [199]:
tree_borough_join_final.to_json("tree_borough_data.json",orient='records')

In [200]:
#Filter top 10 per Boroughs

top10_per_borough = (
    tree_borough_join_final.sort_values(["borough", "Tree Value Score"], ascending= [True, False])
    .groupby("borough")
    .head(10)
    .reset_index(drop=True)
)

top10_per_borough.to_json("Filtered_Trees.json", orient="records")

print("Exported: boroughs_with_top_trees.json")

Exported: boroughs_with_top_trees.json

In [201]:
import pandas as pd
import json

# --- 0) Pick the base dataframe ONCE (so you don't mix df vs tree_borough_join_final)
base = tree_borough_join_final

# --- 1) Top 10 trees per borough
top10 = (
    base.sort_values(["borough", "Tree Value Score"], ascending=[True, False])
        .groupby("borough", as_index=False)
        .head(10)
        .reset_index(drop=True)
)

# Choose fields (REMOVE duplicates like "location" twice)
tree_cols = [
    "borough", "uniqueid", "Tree", "taxon_species", "lat", "lon",
    "TreeRent", "location", "height", "girth",
    "Food squirrels can eat (Yes / No)", "Tree Value Score", "Rank"
]

# Keep only existing cols
tree_cols = [c for c in tree_cols if c in top10.columns]

# IMPORTANT: ensure the dataframe has unique column names (drop duplicate columns)
top10_trees = top10.loc[:, ~top10.columns.duplicated()].copy()

# Now select your fields (also ensure uniqueness here too)
top10_trees = top10_trees[tree_cols].copy()

# --- 2) Borough summary layer (use SAME base df)
borough_summary = (
    base.groupby("borough")
        .agg(
            tree_count=("uniqueid", "count"),
            most_common_tree=("Tree", lambda s: s.mode().iat[0] if not s.mode().empty else None)
        )
        .reset_index()
)

# --- 3) Nest trees WITHOUT groupby.apply (avoids deprecation warning)
trees_by_borough = {
    b: g.drop(columns=["borough"], errors="ignore").to_dict(orient="records")
    for b, g in top10_trees.groupby("borough")
}

# --- 4) Build final structure
output = {
    "boroughs": [
        {
            "borough": row["borough"],
            "tree_count": int(row["tree_count"]),
            "most_common_tree": row["most_common_tree"],
            "trees": trees_by_borough.get(row["borough"], [])
        }
        for _, row in borough_summary.iterrows()
    ]
}

# --- 5) Export JSON
with open("boroughs_with_top_trees.json", "w") as f:
    json.dump(output, f, indent=2)

print("Exported: boroughs_with_top_trees.json")

Exported: boroughs_with_top_trees.json

In [202]:
tree_borough_join_final.loc[tree_borough_join_final["height"].idxmax()]

borough                                      Barnet
lat                                       51.656461
lon                                        -0.20436
uniqueid                                      10832
taxon_species                        Betula pendula
Tree                                   Silver Birch
taxon_genus                                  Betula
common_genus                                  Birch
gla_name                                      Birch
taxon_family                             Betulaceae
maintainer                                LB Barnet
location                                   Highways
climate_suitability                             Low
cs_confidence                                  High
age_cat                                Not provided
canopy_m                                        3 m
height_m                                       45 m
girth_dbh                                     12 cm
girth                                          12.0
canopy                                          3.0
height                                         45.0
Food squirrels can eat (Yes / No)               Yes
Borough House Prices (nov 2025)             603,111
Borough_Nut_Rent                              819.0
P10_girth_borough                               6.0
P90_girth_borough                              65.0
GirthIndex                                 0.101695
AgeFactor                                  0.940678
TreeRent                                 770.415254
CanopyScore                                0.076923
HeightScore                                     1.0
GirthScore                                 0.040134
StructureScore                             0.342809
FoodScore                                         1
location_cat                                      2
SiteFactor                                      0.7
Tree Value Score                          61.140468
Rank                                       121452.0
Name: 12511, dtype: object